service: serverless
frameworkVersion: "3"

custom:
  stage: ${opt:stage, 'dev'}
  env: ${file(./env.yml):}

package:
  individually: true
  include:
    - node_modules/**    
  exclude:
    - .git/**
    - .gitignore
    - .DS_Store

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    HASURA_GRAPHQL_URL: ${self:custom.env.HASURA_GRAPHQL_URL}
    HASURA_ADMIN_SECRET: ${self:custom.env.HASURA_ADMIN_SECRET}
    SQS_QUEUE_URL: { Ref: ReminderQueue }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "cognito-idp:AdminInitiateAuth"
        - "cognito-idp:AdminRespondToAuthChallenge"
        - "sqs:SendMessage"  
        - "sqs:ReceiveMessage"  
      Resource: "*"

functions:
  addTodo:
    handler: lambdas/addTodo.handler
    name: ${self:custom.stage}-${self:custom.env.ADD_TODO_FUNCTION_NAME}
    events:
      - http:
          path: todo
          method: post
          cors:
            origins:
              - http://localhost:3000
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            authorizerId:
              Ref: ApiGatewayAuthorizer
  
  aiAdminQuery:
    handler: lambdas/aiAdminQuery.handler
    name: ${self:custom.stage}-${self:custom.env.AI_ADMIN_QUERY_FUNCTION_NAME}
    events:
      - http:
          path: admin/query
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            authorizerId:
              Ref: ApiGatewayAuthorizer
    
  aiUserQuery:
    handler: lambdas/aiUserQuery.handler
    name: ${self:custom.stage}-${self:custom.env.AI_USER_QUERY_FUNCTION_NAME}
    events:
      - http:
          path: user/query
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            authorizerId:
              Ref: ApiGatewayAuthorizer

  editTodo:
    handler: lambdas/editTodo.handler
    name: ${self:custom.stage}-${self:custom.env.EDIT_TODO_FUNCTION_NAME}
    events:
      - http:
          path: todo
          method: put
          cors:
            origins:
              - http://localhost:3000
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            authorizerId:
              Ref: ApiGatewayAuthorizer

  deleteTodo:
    handler: lambdas/deleteTodo.handler
    name: ${self:custom.stage}-${self:custom.env.DELETE_TODO_FUNCTION_NAME}
    events:
      - http:
          path: todo
          method: delete
          cors:
            origins:
              - http://localhost:3000
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            authorizerId:
              Ref: ApiGatewayAuthorizer

  jwtClaims:
    handler: lambdas/jwtClaims.handler
    name: ${self:custom.stage}-${self:custom.env.JWT_CLAIM_FUNCTION_NAME}
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-${self:custom.env.AWS_USER_POOL_NAME}
          trigger: PreTokenGeneration
          existing: true
  
  syncUsers:
    handler: lambdas/syncUsers.handler
    name: ${self:custom.stage}-${self:custom.env.SYNC_USERS_FUNCTION_NAME}
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-${self:custom.env.AWS_USER_POOL_NAME}
          trigger: PostAuthentication
          existing: true

  cronPushMessages:
    handler: lambdas/cronPushMessages.handler
    events:
      - schedule: rate(600 minutes)

  sendEmails:
    handler: lambdas/sendEmails.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ReminderQueue
              - Arn

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.stage}-${self:custom.env.AWS_USER_POOL_NAME}
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.stage}-${self:custom.env.AWS_USER_POOL_CLIENT_NAME}
        GenerateSecret: false
        UserPoolId:
          Ref: UserPool
        AccessTokenValidity: 86400
        IdTokenValidity: 86400
        TokenValidityUnits:
          AccessToken: "seconds"
          IdToken: "seconds"
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"

    IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.stage}-${self:custom.env.AWS_IDENTITY_POOL_NAME}
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId:
              Ref: UserClient
            ProviderName:
              Fn::GetAtt: ["UserPool", "ProviderName"]

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoUserPool
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - Fn::GetAtt:
              - UserPool
              - Arn

    ReminderQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: reminderQueue